package fixpr

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/models"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/runtime"
)

// generateWithAgent produces a fix by running a coding-agent CLI in a real clone
// of the source repo. The agent can touch multiple files and (when allowed) run
// the build and tests while fixing. A reviewer model gates the result; a
// rejected change re-runs the agent with the objections, up to critiqueRetries.
// The accepted fix flows through the verify / open-PR / preview path.
func generateWithAgent(ctx context.Context, gp genParams, p models.PatternAnalysis) (*proposedFix, error) {
	a := gp.agent
	if a != nil && a.SharedModelEndpoint && a.API == "responses" {
		return nil, fmt.Errorf("agent fix generation with the local OpenCode runtime requires Chat Completions; use ai.api=chat_completions or select the Orka fix runtime")
	}
	if a == nil || a.Runtime == nil {
		return nil, fmt.Errorf("agent fix generation: no agent runtime configured")
	}
	var reviewFeedback string
	for attempt := 0; ; attempt++ {
		res, err := a.Runtime.Generate(ctx, runtime.GenerateSpec{
			Repo:        runtime.RepoRef{Owner: gp.owner, Name: gp.repo, Ref: gp.ref, Token: a.GitToken},
			Instruction: agentInstruction(p, gp.instruction, reviewFeedback, gp.maxFiles, a.AllowBash),
			Model:       a.Model,
			Endpoint:    a.Endpoint,
			Token:       a.ModelToken,
			MaxTurns:    a.MaxTurns,
			AllowBash:   a.AllowBash,
			Timeout:     a.Timeout,
		})
		if err != nil {
			if errors.Is(err, runtime.ErrUnavailable) {
				return nil, fmt.Errorf("agent fix generation unavailable: %w", err)
			}
			return nil, fmt.Errorf("agent fix generation: %w", err)
		}
		if len(res.Files) == 0 {
			return nil, fmt.Errorf("the coding agent produced no code change for this failure (its fix may be operational rather than a code edit)")
		}
		if gp.maxFiles > 0 && len(res.Files) > gp.maxFiles {
			return nil, fmt.Errorf("the coding agent changed %d files, exceeding max_files=%d; dropping as too broad for review", len(res.Files), gp.maxFiles)
		}
		rationale := strings.TrimSpace(p.SuggestedFix)
		if rationale == "" {
			rationale = "Fix generated by the coding agent from the failure's root cause."
		}
		fix := &proposedFix{files: res.Files, diff: res.Diff, rationale: rationale}

		if gp.critique == nil || gp.critiqueRetries == 0 {
			return fix, nil
		}
		issues, err := critiqueAgentFix(ctx, gp.critique, p, res.Files, res.Diff)
		if err != nil {
			return nil, fmt.Errorf("fix review failed: %w", err)
		}
		if issues == "" {
			return fix, nil
		}
		if attempt >= gp.critiqueRetries {
			return nil, fmt.Errorf("agent fix rejected by review after %d attempt(s): %s", attempt+1, oneLine(issues))
		}
		reviewFeedback = issues
	}
}

// critiqueAgentFix asks a reviewer model whether the agent's change has concrete
// defects. It sees the diff plus the full changed file(s) so it can judge
// context. Returns a "; "-joined issue string, empty when the change is
// acceptable.
func critiqueAgentFix(ctx context.Context, c Completer, p models.PatternAnalysis, files map[string]string, diff string) (string, error) {
	var sb strings.Builder
	sb.WriteString(diff)
	sb.WriteString("\n\n")
	for _, path := range sortedKeys(files) {
		fmt.Fprintf(&sb, "=== FILE AFTER CHANGE: %s ===\n%s\n", path, files[path])
	}
	user := fmt.Sprintf(`Root cause: %s
Suggested fix: %s

Proposed change:
%s
Does this change have concrete defects (not style)? Answer with one line of JSON, no comments. Use an empty array if it is a reasonable fix:
{"issues": ["<problem>", "<problem>"]}`,
		oneLine(p.SharedRootCause), oneLine(p.SuggestedFix), sb.String())

	out, err := c.Complete(ctx, critiqueSystemPrompt, user)
	if err != nil {
		return "", err
	}
	var v struct {
		Issues []string `json:"issues"`
	}
	if err := parseJSONObject(out, &v); err != nil {
		return "", fmt.Errorf("review response: %w", err)
	}
	return strings.Join(dedupeNonEmpty(v.Issues), "; "), nil
}

// agentInstruction composes the fix task for the coding agent from the pattern,
// enforcing the guardrails: minimal, targeted, no unrelated reformatting, and
// decline when the fix is not a code change. reviewFeedback, when non-empty,
// carries a prior reviewer's objections for a retry.
func agentInstruction(p models.PatternAnalysis, maintainer, reviewFeedback string, maxFiles int, allowBash bool) string {
	var b strings.Builder
	b.WriteString("A CI failure recurs systematically in this repository. Make the MINIMAL code change that fixes its root cause.\n\n")
	if s := strings.TrimSpace(p.SharedRootCause); s != "" {
		b.WriteString("Root cause:\n" + s + "\n\n")
	} else if s := strings.TrimSpace(p.Summary); s != "" {
		b.WriteString("Failure summary:\n" + s + "\n\n")
	}
	if s := strings.TrimSpace(p.SuggestedFix); s != "" {
		b.WriteString("Suggested direction:\n" + s + "\n\n")
	}
	if len(p.RelevantFiles) > 0 {
		b.WriteString("Files the analysis implicated (starting points, verify before editing):\n")
		for _, f := range p.RelevantFiles {
			b.WriteString("- " + f + "\n")
		}
		b.WriteString("\n")
	}
	b.WriteString("Rules:\n")
	b.WriteString("- Make the smallest change that fixes the root cause. Prefer configuration, template, or manifest files.\n")
	b.WriteString("- Do not reformat or touch unrelated code.\n")
	if maxFiles > 0 {
		fmt.Fprintf(&b, "- Change at most %d file(s).\n", maxFiles)
	}
	if allowBash {
		b.WriteString("- You may run the build and tests to confirm the change compiles and does not regress.\n")
	}
	b.WriteString("- If the failure is operational (infrastructure, quota, or timing) and cannot be fixed by a code change, make NO change.\n")
	if m := strings.TrimSpace(maintainer); m != "" {
		b.WriteString("\nMaintainer instruction (follow it): " + m + "\n")
	}
	if r := strings.TrimSpace(reviewFeedback); r != "" {
		b.WriteString("\nA previous attempt was rejected by review. Address these problems: " + r + "\n")
	}
	return b.String()
}
