package fixpr

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/models"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/runtime"
)

// generateWithAgent produces a fix by running a coding-agent CLI in a real clone
// of the source repo, instead of the anchored single-file edit generator. The
// agent can touch multiple files and (when allowed) run the build and tests
// while fixing. The result flows through the same verify / open-PR / preview
// path as the default generator.
func generateWithAgent(ctx context.Context, gp genParams, p models.PatternAnalysis) (*proposedFix, error) {
	a := gp.agent
	res, err := a.Runtime.Generate(ctx, runtime.GenerateSpec{
		Repo:        runtime.RepoRef{Owner: gp.owner, Name: gp.repo, Ref: gp.ref, Token: a.GitToken},
		Instruction: agentInstruction(p, gp.instruction, gp.maxFiles, a.AllowBash),
		Model:       a.Model,
		Endpoint:    a.Endpoint,
		Token:       a.ModelToken,
		MaxTurns:    a.MaxTurns,
		AllowBash:   a.AllowBash,
		Timeout:     a.Timeout,
	})
	if err != nil {
		if errors.Is(err, runtime.ErrUnavailable) {
			return nil, fmt.Errorf("agent fix generation unavailable: %w", err)
		}
		return nil, fmt.Errorf("agent fix generation: %w", err)
	}
	if len(res.Files) == 0 {
		return nil, fmt.Errorf("the coding agent produced no code change for this failure (its fix may be operational rather than a code edit)")
	}
	if gp.maxFiles > 0 && len(res.Files) > gp.maxFiles {
		return nil, fmt.Errorf("the coding agent changed %d files, exceeding max_files=%d; dropping as too broad for review", len(res.Files), gp.maxFiles)
	}
	rationale := strings.TrimSpace(p.SuggestedFix)
	if rationale == "" {
		rationale = "Fix generated by the coding agent from the failure's root cause."
	}
	return &proposedFix{files: res.Files, diff: res.Diff, rationale: rationale}, nil
}

// agentInstruction composes the fix task for the coding agent from the pattern,
// carrying the same guardrails the anchored generator's prompts enforce:
// minimal, targeted, no unrelated reformatting, and decline when the fix is not
// a code change.
func agentInstruction(p models.PatternAnalysis, maintainer string, maxFiles int, allowBash bool) string {
	var b strings.Builder
	b.WriteString("A CI failure recurs systematically in this repository. Make the MINIMAL code change that fixes its root cause.\n\n")
	if s := strings.TrimSpace(p.SharedRootCause); s != "" {
		b.WriteString("Root cause:\n" + s + "\n\n")
	} else if s := strings.TrimSpace(p.Summary); s != "" {
		b.WriteString("Failure summary:\n" + s + "\n\n")
	}
	if s := strings.TrimSpace(p.SuggestedFix); s != "" {
		b.WriteString("Suggested direction:\n" + s + "\n\n")
	}
	if len(p.RelevantFiles) > 0 {
		b.WriteString("Files the analysis implicated (starting points, verify before editing):\n")
		for _, f := range p.RelevantFiles {
			b.WriteString("- " + f + "\n")
		}
		b.WriteString("\n")
	}
	b.WriteString("Rules:\n")
	b.WriteString("- Make the smallest change that fixes the root cause. Prefer configuration, template, or manifest files.\n")
	b.WriteString("- Do not reformat or touch unrelated code.\n")
	if maxFiles > 0 {
		fmt.Fprintf(&b, "- Change at most %d file(s).\n", maxFiles)
	}
	if allowBash {
		b.WriteString("- You may run the build and tests to confirm the change compiles and does not regress.\n")
	}
	b.WriteString("- If the failure is operational (infrastructure, quota, or timing) and cannot be fixed by a code change, make NO change.\n")
	if m := strings.TrimSpace(maintainer); m != "" {
		b.WriteString("\nMaintainer instruction (follow it): " + m + "\n")
	}
	return b.String()
}
