import { useEffect, useMemo, useState } from "react";
import Paid from "@mui/icons-material/Paid";
import Download from "@mui/icons-material/Download";
import Alert from "@mui/material/Alert"; import Box from "@mui/material/Box";
import Button from "@mui/material/Button"; import Chip from "@mui/material/Chip";
import CircularProgress from "@mui/material/CircularProgress"; import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack"; import TextField from "@mui/material/TextField"; import Typography from "@mui/material/Typography";
import { Panel } from "../components/Panel"; import { useAuth } from "../hooks/useAuth"; import { useCapabilities } from "../hooks/useCapabilities";
import { featureLabels, formatCost, formatTokens, totalTokens, usageQuery } from "../lib/aiUsage";
import type { AIUsageFeature, AIUsageReport, AIUsageTotals } from "../types/usage";
const API_BASE = import.meta.env.BASE_URL;
const today = () => new Date().toISOString().slice(0, 10);
const daysAgo = (days: number) => { const d = new Date(); d.setUTCDate(d.getUTCDate() - days); return d.toISOString().slice(0, 10); };
function Stat({ label, value, note }: { label: string; value: string; note?: string }) { return <Panel sx={{ p: 2.25 }}><Typography variant="overline" color="text.secondary">{label}</Typography><Typography variant="h4" sx={{ mt: .4, fontVariantNumeric: "tabular-nums" }}>{value}</Typography>{note && <Typography variant="caption" color="text.secondary">{note}</Typography>}</Panel>; }
function Bar({ value, max }: { value: number; max: number }) { return <Box sx={{ height: 7, borderRadius: 9, bgcolor: "action.hover", overflow: "hidden" }}><Box sx={{ width: `${max ? Math.max(2, value / max * 100) : 0}%`, height: "100%", bgcolor: "primary.main", borderRadius: 9 }} /></Box>; }
const zeroTotals: AIUsageTotals = { operations:0,cache_hits:0,failures:0,external_unmetered_operations:0,model_requests:0,reported_requests:0,unreported_requests:0,input_tokens:0,cached_input_tokens:0,output_tokens:0,reasoning_tokens:0,estimated_cost_nanos:"0" };
export function AIUsagePage() {
 const { features } = useCapabilities(); const auth = useAuth(); const [start,setStart]=useState(daysAgo(29)); const [end,setEnd]=useState(today()); const [feature,setFeature]=useState<AIUsageFeature|"">(""); const [loaded,setLoaded]=useState<{key:string|null;data:AIUsageReport|null;error:string}>({key:null,data:null,error:""});
 const query=usageQuery(start,end,feature||undefined);
 useEffect(()=>{ if(!features.ai_usage||auth.status!=="authenticated")return; const c=new AbortController(); fetch(`${API_BASE}api/ai-usage?${query}`,{credentials:"same-origin",signal:c.signal}).then(async r=>{if(r.status===404)return null;if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json() as Promise<AIUsageReport>}).then(data=>setLoaded({key:query,data,error:""})).catch(e=>{if(!c.signal.aborted)setLoaded({key:query,data:null,error:e instanceof Error?e.message:"Unable to load usage"})}); return()=>c.abort();},[auth.status,features.ai_usage,query]);
 const data=loaded.key===query?loaded.data:null; const error=loaded.key===query?loaded.error:""; const loading=auth.status==="authenticated"&&loaded.key!==query; const totals=data?.totals??zeroTotals; const maxDaily=useMemo(()=>Math.max(0,...(data?.daily??[]).map(d=>totalTokens(d.totals))),[data]);
 if(!features.ai_usage)return <Alert severity="info">Private AI usage reporting is not available in this deployment.</Alert>;
 if(auth.status==="loading")return <Box sx={{display:"grid",placeItems:"center",py:10}}><CircularProgress size={28}/></Box>;
 if(auth.status==="anonymous")return <Panel sx={{maxWidth:620,mx:"auto",p:4,textAlign:"center"}}><Paid sx={{fontSize:38,color:"primary.main"}}/><Typography variant="h5">Operator sign-in required</Typography><Typography color="text.secondary" sx={{my:2}}>Token usage and cost estimates are private operational data.</Typography><Button variant="contained" onClick={auth.signIn}>Sign in to view usage</Button></Panel>;
 return <Stack spacing={2.5}>
  <Stack direction={{xs:"column",md:"row"}} sx={{justifyContent:"space-between",gap:2}}><Box><Stack direction="row" sx={{gap:1,alignItems:"center"}}><Paid color="primary"/><Typography variant="h4">AI Usage</Typography></Stack><Typography color="text.secondary">Provider-reported tokens and operator-configured cost estimates.</Typography></Box><Button component="a" href={`${API_BASE}api/ai-usage/download?${query}`} startIcon={<Download/>} variant="outlined">Download JSON</Button></Stack>
  <Panel sx={{p:2,display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(3,1fr)"},gap:1.5}}><TextField type="date" label="Start" value={start} onChange={e=>setStart(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="End" value={end} onChange={e=>setEnd(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField select label="Feature" value={feature} onChange={e=>setFeature(e.target.value as AIUsageFeature|"")}><MenuItem value="">All features</MenuItem>{Object.entries(featureLabels).map(([k,v])=><MenuItem key={k} value={k}>{v}</MenuItem>)}</TextField></Panel>
  {error&&<Alert severity="error">{error}</Alert>}{loading?<Box sx={{display:"grid",placeItems:"center",py:8}}><CircularProgress size={26}/></Box>:!data&&!error?<Alert severity="info">No AI usage has been recorded yet.</Alert>:data&&<>
   <Stack direction="row" sx={{gap:1,flexWrap:"wrap"}}><Chip label={`${data.coverage.status} estimate`} color={data.coverage.status==="complete"?"success":data.coverage.status==="partial"?"warning":"default"}/>{data.mixed_pricing&&<Chip label="Mixed pricing" variant="outlined"/>}{totals.external_unmetered_operations>0&&<Chip label={`${totals.external_unmetered_operations} external unmetered`} color="warning" variant="outlined"/>}</Stack>
   <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(2,1fr)",lg:"repeat(4,1fr)"},gap:1.5}}><Stat label="Estimated cost" value={data.mixed_currency?"Mixed currencies":formatCost(totals.estimated_cost_nanos,data.currency)} note={data.mixed_currency?"Use the JSON report for currency-specific records":data.coverage.status!=="complete"?"Coverage is incomplete":undefined}/><Stat label="Total tokens" value={formatTokens(totalTokens(totals))}/><Stat label="Input / output" value={`${formatTokens(totals.input_tokens)} / ${formatTokens(totals.output_tokens)}`}/><Stat label="Model requests" value={formatTokens(totals.model_requests)} note={`${totals.reported_requests} reported`}/></Box>
   <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",lg:"1.2fr .8fr"},gap:2}}><Panel sx={{p:2.5}}><Typography variant="h6" sx={{mb:2}}>Daily activity</Typography><Stack spacing={1.5}>{data.daily.map(d=><Box key={d.date} sx={{display:"grid",gridTemplateColumns:"92px 1fr 74px",gap:1.5,alignItems:"center"}}><Typography variant="caption" sx={{fontFamily:"monospace"}}>{d.date.slice(5)}</Typography><Bar value={totalTokens(d.totals)} max={maxDaily}/><Typography variant="caption" sx={{textAlign:"right"}}>{formatTokens(totalTokens(d.totals))}</Typography></Box>)}{data.daily.length===0&&<Typography color="text.secondary">No usage in this range.</Typography>}</Stack></Panel><Panel sx={{p:2.5}}><Typography variant="h6" sx={{mb:2}}>By feature</Typography><Stack spacing={1.6}>{data.features.map(row=><Box key={row.feature}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography variant="body2" sx={{fontWeight:700}}>{featureLabels[row.feature]}</Typography><Typography variant="caption">{formatTokens(totalTokens(row.totals))}</Typography></Stack><Bar value={totalTokens(row.totals)} max={Math.max(...data.features.map(f=>totalTokens(f.totals)),1)}/></Box>)}</Stack></Panel></Box>
  </>}</Stack>;
}
