package onboard

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/ai"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/models"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/prow/jobconfig"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/prowbuild"
	"github.com/willie-yao/prow-ai-dashboard/backend/internal/storage"
)

// k8sCILogsBucket is the default artifact bucket for Kubernetes TestGrid jobs.
const k8sCILogsBucket = "kubernetes-ci-logs"

// Deploy modes the scaffold targets.
const (
	modePages = "pages"
	modeK8s   = "k8s"
)

func scaffoldGuide(mode string) string {
	if mode == modeK8s {
		return "deploy/README.md"
	}
	return "CHECKLIST.md"
}

// scaffoldPRBody is the PR description: a short summary plus the human steps.
func scaffoldPRBody(name, mode string, aiEnabled bool) string {
	guide := "`" + scaffoldGuide(mode) + "`"
	finalStep := "Complete the GitHub configuration in `CHECKLIST.md` and enable Pages."
	if aiEnabled {
		finalStep = "Complete the GitHub configuration in `CHECKLIST.md` (enable Pages, set the AI provider variables and token)."
	}
	if mode == modeK8s {
		finalStep = "Fill in `deploy/values.yaml`, then follow `deploy/README.md` to install the dashboard with Helm."
	}
	return fmt.Sprintf("Generated by `prow-ai-dashboard onboard` for **%s**. The job sweep confirmed discovery finds jobs.\n\n"+
		"**Before merging or deploying:**\n"+
		"- Review and fill in `prompts/system.md`.\n"+
		"- Review or trim the inferred `categories` in `project.yaml`.\n"+
		"- %s\n\n"+
		"See %s for the full steps.", name, finalStep, guide)
}

// buildSystemPrompt drafts prompts/system.md from source docs when experimental
// API drafting is selected. Failures fall back to the reviewable TODO template.
func buildSystemPrompt(ctx context.Context, opts Options, data scaffoldData, input promptDraftInput, out, errOut io.Writer) (string, promptPreparationResult, error) {
	started := time.Now()
	debug := newPromptDebugger(opts.PromptDebug, errOut, opts.AIToken, opts.GitHubToken)
	defer debug.total(started)

	if requestedPromptPreparation(opts) == promptRequestTemplate {
		if opts.AIToken == "" && !opts.NoPrompt {
			fmt.Fprintln(out, "[info] no AI token is set; writing a prompts/system.md TODO template")
		}
		prompt, err := render(systemPromptTmpl, data)
		return prompt, newTemplatePromptResult(), err
	}

	preflightStart := time.Now()
	if opts.AIToken == "" {
		failure := &promptPreparationFailure{Stage: promptStageTokenPreflight, Category: promptFailureMissingToken}
		debug.stage(promptStageTokenPreflight, time.Since(preflightStart))
		return promptFallback(opts, data, errOut, debug, failure)
	}
	if strings.TrimSpace(opts.AIEndpoint) == "" || strings.TrimSpace(opts.AIModel) == "" {
		failure := &promptPreparationFailure{Stage: promptStageTokenPreflight, Category: promptFailureMissingCoordinates}
		debug.stage(promptStageTokenPreflight, time.Since(preflightStart))
		return promptFallback(opts, data, errOut, debug, failure)
	}
	debug.stage(promptStageTokenPreflight, time.Since(preflightStart))
	debug.provider(opts)

	// Bound the whole drafting phase so a hung endpoint degrades to the template
	// instead of hanging the command.
	ctx, cancel := context.WithTimeout(ctx, effectivePromptDraftTimeout(opts))
	defer cancel()

	httpClient := &http.Client{Timeout: 30 * time.Second}
	fmt.Fprintf(out, "Drafting prompts/system.md from %s source evidence...\n", input.SourceRepo.FullName)
	// Empty GitHub token means anonymous public reads. AI_TOKEN is used only by
	// the configured prompt-drafting provider.
	sourceResult, err := fetchPromptSourcesDetailed(ctx, httpClient, input.SourceRepo, input.Jobs, opts.GitHubToken, opts.AIToken, opts.GitHubToken)
	debug.stage(promptStageSourceRevision, sourceResult.RevisionDuration)
	debug.stage(promptStageSourceTree, sourceResult.TreeDuration)
	debug.stage(promptStageSourceExcerpt, sourceResult.ExcerptDuration)
	for _, source := range sourceResult.Sources {
		debug.source(source)
	}
	debug.sourceSummary(sourceResult.Sources, len(input.Jobs), sourceResult.Attempts)
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return "", promptPreparationResult{}, err
		}
		failure := promptFailureFromError(promptStageSourceExcerpt, err)
		return promptFallback(opts, data, errOut, debug, failure)
	}
	redactPromptCredentials(sourceResult.Sources, opts.AIToken, opts.GitHubToken)
	input.Sources = sourceResult.Sources
	if !hasMeaningfulPromptSources(input.Sources) {
		failure := &promptPreparationFailure{Stage: promptStageSourceExcerpt, Category: promptFailureNoSourceEvidence}
		return promptFallback(opts, data, errOut, debug, failure)
	}

	client := ai.NewClientWithOptions(ai.Options{
		Token:    opts.AIToken,
		API:      opts.AIAPI,
		Endpoint: opts.AIEndpoint,
		Model:    opts.AIModel,
	})
	generation, err := generatePromptBodyDetailed(ctx, client, input, opts.AIToken, opts.GitHubToken)
	debug.stage(promptStageEvidenceExtraction, generation.ExtractionDuration)
	debug.stage(promptStageStructuredRevision, generation.RevisionDuration)
	debug.stage(promptStageFinalPromptValidation, generation.RenderDuration)
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return "", promptPreparationResult{}, err
		}
		failure := promptFailureFromError(promptStageEvidenceExtraction, err)
		return promptFallback(opts, data, errOut, debug, failure)
	}

	result := newAPIPromptResult()
	if generation.RevisionFallback {
		result.RevisionFallback = true
		debug.failure(generation.RevisionFailure)
		writePromptFailure(errOut, "prompts/system.md revision failed", generation.RevisionFailure, "first validated evidence extraction")
	}
	fmt.Fprintf(out, "Drafted prompts/system.md from %d source(s) and %d Prow job(s). Review it before deployment.\n", len(input.Sources), len(input.Jobs))
	return composeGeneratedPrompt(data.Name, generation.Body), result, nil
}

func promptFailureFromError(defaultStage promptPreparationStage, err error) *promptPreparationFailure {
	var failure *promptPreparationFailure
	if errors.As(err, &failure) {
		return failure
	}
	return classifyPromptFailure(defaultStage, err)
}

func promptFallback(opts Options, data scaffoldData, errOut io.Writer, debug promptDebugger, failure *promptPreparationFailure) (string, promptPreparationResult, error) {
	debug.failure(failure)
	writePromptFailure(errOut, "prompts/system.md generation failed", failure, "reviewable TODO template")
	result := newAPIFallbackResult(failure)
	if opts.RequirePromptDraft {
		return "", result, &requiredPromptDraftError{failure: failure}
	}
	prompt, err := render(systemPromptTmpl, data)
	return prompt, result, err
}

const (
	defaultPromptDraftTimeout = 5 * time.Minute
	minPromptDraftTimeout     = time.Minute
	maxPromptDraftTimeout     = 2 * time.Hour
)

func effectivePromptDraftTimeout(opts Options) time.Duration {
	if opts.PromptTimeout <= 0 {
		return defaultPromptDraftTimeout
	}
	return opts.PromptTimeout
}

func validateOptions(opts *Options) error {
	if err := validateCredentialSeparation(*opts); err != nil {
		return err
	}
	if err := project.ValidateAIAPI(opts.AIAPI); err != nil {
		return err
	}
	if err := project.ValidateAIAPI(opts.DeploymentAIAPI); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	if err := validateAIEndpoint(opts.AIEndpoint); err != nil {
		return err
	}
	if err := validateAIEndpoint(opts.DeploymentAIEndpoint); err != nil {
		return fmt.Errorf("deployed %w", err)
	}
	opts.AIAPI = strings.ToLower(strings.TrimSpace(opts.AIAPI))
	if opts.AIAPI == "" {
		opts.AIAPI = project.AIAPIChatCompletions
	}
	opts.DeploymentAIAPI = strings.ToLower(strings.TrimSpace(opts.DeploymentAIAPI))
	if opts.PromptTimeout == 0 {
		opts.PromptTimeout = defaultPromptDraftTimeout
	}
	if opts.PromptTimeout < minPromptDraftTimeout || opts.PromptTimeout > maxPromptDraftTimeout {
		return fmt.Errorf("--prompt-timeout must be between %s and %s", minPromptDraftTimeout, maxPromptDraftTimeout)
	}
	if (opts.TestGrid == "") == (opts.Bucket == "") {
		return fmt.Errorf("provide exactly one of --testgrid or --bucket")
	}
	if _, _, err := parseRepo(opts.DashboardRepo); err != nil {
		return fmt.Errorf("--dashboard-repo %w", err)
	}
	sourceRepo, err := NormalizeGitHubRepo(opts.SourceRepo)
	if err != nil {
		return fmt.Errorf("--source-repo %w", err)
	}
	opts.SourceRepo = sourceRepo.FullName
	if opts.GCSWebBase != "" && opts.Bucket == "" {
		return fmt.Errorf("--gcsweb-base only applies with --bucket")
	}
	if opts.OpenPR && opts.UpdateExisting {
		return fmt.Errorf("--update-existing applies only to local output and cannot be combined with --open-pr")
	}
	if opts.RequirePromptDraft && opts.NoPrompt {
		return fmt.Errorf("--require-prompt-draft is valid only when experimental API prompt drafting is selected")
	}
	if opts.RequirePromptDraft && opts.AIToken == "" {
		return fmt.Errorf("AI_TOKEN is required because it authenticates experimental API prompt drafting")
	}
	// API drafting needs explicit provider coordinates. Without an API request,
	// onboarding writes the reviewable TODO template.
	if requestedPromptPreparation(*opts) == promptRequestAPIExperimental {
		if opts.AIEndpoint == "" || opts.AIModel == "" {
			return fmt.Errorf("experimental API prompt drafting needs AI_ENDPOINT and AI_MODEL set; AI_TOKEN authenticates that provider")
		}
	}
	if opts.EngineRef == "" {
		opts.EngineRef = "main"
	}
	switch opts.Mode {
	case "":
		opts.Mode = modePages
	case modePages, modeK8s:
	default:
		return fmt.Errorf("--mode must be %q or %q, got %q", modePages, modeK8s, opts.Mode)
	}
	if opts.OutDir == "" {
		_, name, _ := parseRepo(opts.DashboardRepo)
		opts.OutDir = name
	}
	opts.OutDir = filepath.Clean(opts.OutDir)
	return nil
}

func validateCredentialSeparation(opts Options) error {
	values := []string{
		opts.TestGrid, opts.Bucket, opts.GCSWebBase, opts.DashboardRepo, opts.SourceRepo,
		opts.ID, opts.Name, opts.ShortName, opts.EngineRef, opts.OutDir,
		opts.AIAPI, opts.AIEndpoint, opts.AIModel,
		opts.DeploymentAIAPI, opts.DeploymentAIEndpoint, opts.DeploymentAIModel,
	}
	for _, credential := range []string{opts.AIToken, opts.GitHubToken} {
		if credential == "" {
			continue
		}
		for _, value := range values {
			if strings.Contains(value, credential) {
				return fmt.Errorf("a credential was supplied in a nonsecret onboarding field; keep tokens in environment variables only")
			}
		}
	}
	return nil
}

func validateAIEndpoint(endpoint string) error {
	if strings.TrimSpace(endpoint) == "" {
		return nil
	}
	parsed, err := url.Parse(endpoint)
	if err != nil {
		return fmt.Errorf("AI_ENDPOINT is not a valid URL")
	}
	if (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return fmt.Errorf("AI_ENDPOINT must be an absolute HTTP or HTTPS URL")
	}
	if parsed.User != nil {
		return fmt.Errorf("AI_ENDPOINT must not contain credentials; use AI_TOKEN")
	}
	query, err := url.ParseQuery(parsed.RawQuery)
	if err != nil {
		return fmt.Errorf("AI_ENDPOINT contains an invalid query string")
	}
	for key := range query {
		if credentialQueryKey(key) {
			return fmt.Errorf("AI_ENDPOINT must not contain credential query parameters; use AI_TOKEN")
		}
	}
	return nil
}

func credentialQueryKey(key string) bool {
	lower := strings.ToLower(strings.TrimSpace(key))
	for _, fragment := range []string{"token", "secret", "password", "credential", "api-key", "api_key", "apikey", "access-key", "access_key", "subscription-key", "subscription_key", "signature"} {
		if strings.Contains(lower, fragment) {
			return true
		}
	}
	return lower == "key" || lower == "sig" || strings.HasSuffix(lower, "-key") || strings.HasSuffix(lower, "_key")
}

// sweepConfig builds the minimal in-memory config needed to run discovery.
func sweepConfig(opts Options) *project.Config {
	cfg := &project.Config{
		ID:      derivedID(opts),
		Name:    derivedName(opts),
		Storage: project.Storage{Provider: provider(opts), Bucket: bucket(opts), Base: opts.GCSWebBase},
	}
	if opts.TestGrid != "" {
		cfg.TestGrid = project.TestGrid{Dashboard: opts.TestGrid}
	} else {
		cfg.Discovery = project.Discovery{Source: project.DiscoveryBucket}
	}
	return cfg
}

// discover runs the same job discovery the fetcher uses, by source.
func discover(ctx context.Context, cfg *project.Config, includePresubmits bool) ([]models.ProwJob, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	if cfg.EffectiveDiscoverySource() == project.DiscoveryBucket {
		backend, err := storage.New(cfg.StorageConfig(), client)
		if err != nil {
			return nil, fmt.Errorf("configuring storage: %w", err)
		}
		return prowbuild.DiscoverJobs(ctx, backend, includePresubmits, cfg.Discovery.JobFilters)
	}
	jobs, err := jobconfig.FetchJobConfigs(ctx, client, cfg)
	if err != nil {
		return nil, err
	}
	if includePresubmits {
		return jobs, nil
	}
	periodic := jobs[:0]
	for _, j := range jobs {
		if j.JobType == models.JobTypePeriodic {
			periodic = append(periodic, j)
		}
	}
	return periodic, nil
}

func includePresubmits(opts Options) bool {
	return opts.IncludePresubmits != nil && *opts.IncludePresubmits
}

func deploymentAIAPI(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIAPI); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIAPI)
}

func deploymentAIEndpoint(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIEndpoint); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIEndpoint)
}

func deploymentAIModel(opts Options) string {
	if value := strings.TrimSpace(opts.DeploymentAIModel); value != "" {
		return value
	}
	return strings.TrimSpace(opts.AIModel)
}

// buildScaffoldData assembles template input from options and categories.
func buildScaffoldData(opts Options, cats []project.CategoryRule) scaffoldData {
	owner, name := splitRepo(opts.DashboardRepo)
	srcOwner, srcName := splitRepo(opts.SourceRepo)
	mode := opts.Mode
	if mode == "" {
		mode = modePages
	}
	aiEnabled := effectiveAIEnabled(opts)
	aiAPI := deploymentAIAPI(opts)
	if aiAPI == "" || opts.deferDeploymentAI {
		aiAPI = project.AIAPIChatCompletions
	}
	aiEndpoint := deploymentAIEndpoint(opts)
	if aiEndpoint == "" || opts.deferDeploymentAI {
		if aiAPI == project.AIAPIResponses {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/responses"
		} else {
			aiEndpoint = "http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/chat/completions"
		}
	}
	aiModel := deploymentAIModel(opts)
	if aiModel == "" || opts.deferDeploymentAI {
		aiModel = "<your-model-id>"
	}
	d := scaffoldData{
		ID:                derivedID(opts),
		Name:              derivedName(opts),
		ShortName:         opts.ShortName,
		Provider:          provider(opts),
		Bucket:            bucket(opts),
		GCSWebBase:        opts.GCSWebBase,
		Title:             derivedName(opts) + " Prow Dashboard",
		BasePath:          "/" + name,
		SiteURL:           "https://" + owner + ".github.io/" + name,
		SourceOwner:       srcOwner,
		SourceName:        srcName,
		Categories:        cats,
		IncludePresubmits: includePresubmits(opts),
		EngineRef:         opts.EngineRef,
		Mode:              mode,
		AIEnabled:         aiEnabled,
		AIAPI:             aiAPI,
		AIEndpoint:        aiEndpoint,
		AIModel:           aiModel,
		Namespace:         k8sName(derivedID(opts)),
		DashboardName:     name,
	}
	// Kubernetes-native serves at the domain root from the in-cluster server, so
	// there is no gh-pages subpath; site_url is a placeholder until an ingress
	// hostname exists.
	if mode == modeK8s {
		d.BasePath = "/"
		d.SiteURL = "http://localhost:8080"
	}
	if opts.TestGrid != "" {
		d.DiscoveryTestGrid = opts.TestGrid
	} else {
		d.BucketDiscovery = true
	}
	return d
}

func validateGeneratedYAML(yamlText string) error {
	_, err := project.Parse([]byte(yamlText))
	return err
}

func provider(opts Options) string {
	if opts.GCSWebBase != "" {
		return string(storage.ProviderGCSWeb)
	}
	return string(storage.ProviderGCS)
}

func bucket(opts Options) string {
	if opts.Bucket != "" {
		return opts.Bucket
	}
	return k8sCILogsBucket
}

func derivedID(opts Options) string {
	if opts.ID != "" {
		return opts.ID
	}
	_, name := splitRepo(opts.DashboardRepo)
	// Strip a trailing dashboard suffix so the id reads like the project.
	id := strings.TrimSuffix(name, "-prow-ai-dashboard")
	id = strings.TrimSuffix(id, "-prow-dashboard")
	if id == "" {
		id = name
	}
	return id
}

func derivedName(opts Options) string {
	if opts.Name != "" {
		return opts.Name
	}
	return labelFor(derivedID(opts))
}

// k8sName coerces s into a DNS-1123 label safe for a namespace and Helm release
// name: lowercase, non-alphanumerics to '-', collapsed, trimmed, capped at 63.
func k8sName(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	out := strings.Trim(b.String(), "-")
	if len(out) > 63 {
		out = strings.Trim(out[:63], "-")
	}
	if out == "" {
		out = "dashboard"
	}
	return out
}

func splitRepo(repo string) (owner, name string) {
	owner, name, _ = parseRepo(repo)
	return owner, name
}

// parseRepo strictly parses owner/name with one slash and non-empty parts.
func parseRepo(repo string) (owner, name string, err error) {
	parts := strings.Split(repo, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("must be owner/name, got %q", repo)
	}
	return parts[0], parts[1], nil
}

func render(t *template.Template, data any) (string, error) {
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
