package onboard

import (
	"strings"
	"text/template"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root (gcsweb provider only)
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Parse(
	`# Generated by prow-ai-dashboard onboard. Review and edit before deploying.
id: {{.ID}}
name: "{{.Name}}"
{{if .DiscoveryTestGrid}}
# Jobs advertising this testgrid dashboard are discovered automatically.
testgrid:
  dashboard: "{{.DiscoveryTestGrid}}"
{{else}}
# Jobs are discovered by listing the storage bucket's own job indexes.
discovery:
  source: bucket
{{- if .IncludePresubmits}}
{{- end}}
{{end}}
# Where this project's Prow build artifacts live.
storage:
  provider: {{.Provider}}
  bucket: "{{.Bucket}}"
{{- if .GCSWebBase}}
  base: "{{.GCSWebBase}}"
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: "{{.Match}}"
    id: "{{.ID}}"
    label: "{{.Label}}"
{{- end}}
{{end}}
# UI branding.
branding:
  title: "{{.Title}}"
  base_path: "{{.BasePath}}"
  site_url: "{{.SiteURL}}"
  source_repo:
    owner: "{{.SourceOwner}}"
    name: "{{.SourceName}}"
{{if .IncludePresubmits}}
# This project's dashboard includes presubmit jobs.
source:
  include_presubmits: true
{{end}}`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Parse(
	`name: Deploy Dashboard

# Calls the reusable workflow in willie-yao/prow-ai-dashboard to build and
# deploy this repo's Prow dashboard to GitHub Pages.

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: willie-yao/prow-ai-dashboard/.github/workflows/reusable-deploy.yml@{{.EngineRef}}
    with:
      project_dir: "."
      builds: 10
      ai: true
      # Headroom for a cold full re-analysis with the critique retry loop;
      # the AI cache persists partial progress so each run converges.
      fetch-timeout: "150m"
      # Optional: keep model/endpoint out of the public project.yaml by
      # sourcing them from repo variables. The project.yaml ai.* fields win.
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
      # Optional: uncomment to enable the matching feature.
      # SLACK_WEBHOOK_URL: ${{"{{"}} secrets.SLACK_WEBHOOK_URL {{"}}"}}
      # ISSUE_TOKEN: ${{"{{"}} secrets.ISSUE_TOKEN {{"}}"}}
`))

var clearCacheYAMLTmpl = template.Must(template.New("clear-cache.yml").Parse(
	`name: Clear AI Cache

# Manually wipe this repo's data cache so the next deploy refetches
# everything and regenerates AI summaries.

on:
  workflow_dispatch: {}

permissions:
  actions: write

jobs:
  clear:
    uses: willie-yao/prow-ai-dashboard/.github/workflows/reusable-clear-cache.yml@{{.EngineRef}}
    with:
      project_dir: "."
`))

var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. Replace the placeholder below with project-specific
knowledge: the architecture under test, the failure surface, where evidence
lives in the artifacts, and the known transient/flake classes. The richer this
is, the deeper the analysis. See an example at
https://github.com/willie-yao/capz-prow-ai-dashboard/blob/main/prompts/system.md

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe the system under test and how its components relate. -->

## Where the evidence lives

<!-- TODO: name the key artifacts (build-log.txt, per-component logs, resource
dumps) and what each is good for. -->

## Known transient / flake classes

<!-- TODO: list infrastructure flakes that should be classified transient (and
NOT turned into a "real bug" verdict), e.g. registry pull timeouts, quota
exhaustion, API server still starting. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`prow-ai-dashboard onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- ` + "`prompts/system.md`" + ` is a **stub**: fill it in with project-specific
  knowledge. This is the single biggest lever on analysis quality.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow

# Set the AI token secret (a token your chat-completions endpoint accepts):
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}

# Optional: GitHub issue auto-filing (a token with issues:write on the target):
# gh secret set ISSUE_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: Slack notifications:
# gh secret set SLACK_WEBHOOK_URL --repo {{.DashboardOwner}}/{{.DashboardName}}
` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/prow-ai-dashboard/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the (slightly different) input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
