package onboard

import (
	"net/url"
	"strconv"
	"strings"
	"text/template"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	ShortName         string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
	Mode              string // "pages" or "k8s"
	AIEnabled         bool
	AIAPI             string // seeds deploy/values.yaml ai.api (k8s mode)
	AIEndpoint        string // seeds deploy/values.yaml ai.endpoint (k8s mode)
	AIModel           string // seeds deploy/values.yaml ai.model (k8s mode)
	Namespace         string // k8s namespace / helm release name (k8s mode)
	DashboardName     string // dashboard repo name; the scaffold's directory
}

var yamlTemplateFuncs = template.FuncMap{
	"quote":   strconv.Quote,
	"urlPath": url.PathEscape,
}

var readmeTemplateFuncs = template.FuncMap{
	"shellquote": func(value string) string {
		return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
	},
	"urlPath": url.PathEscape,
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# Generated by prow-ai-dashboard onboard. Review and edit before deploying.
id: {{quote .ID}}
name: {{quote .Name}}
{{if .ShortName}}short_name: {{quote .ShortName}}
{{end}}{{if .DiscoveryTestGrid}}
# Jobs advertising this testgrid dashboard are discovered automatically.
testgrid:
  dashboard: {{quote .DiscoveryTestGrid}}
{{else}}
# Jobs are discovered by listing the storage bucket's own job indexes.
discovery:
  source: bucket
{{- if .IncludePresubmits}}
{{- end}}
{{end}}
# Where this project's Prow build artifacts live.
storage:
  provider: {{.Provider}}
  bucket: {{quote .Bucket}}
{{- if .GCSWebBase}}
  base: {{quote .GCSWebBase}}
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: {{quote .Match}}
    id: {{quote .ID}}
    label: {{quote .Label}}
{{- end}}
{{end}}
# UI branding.
branding:
  title: {{quote .Title}}
  base_path: {{quote .BasePath}}
  site_url: {{quote .SiteURL}}
  source_repo:
    owner: {{quote .SourceOwner}}
    name: {{quote .SourceName}}

{{if .IncludePresubmits}}
# This project's dashboard includes presubmit jobs.
source:
  include_presubmits: true
{{end}}`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Funcs(yamlTemplateFuncs).Parse(
	`name: Deploy Dashboard

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: {{quote (printf "willie-yao/prow-ai-dashboard/.github/workflows/reusable-deploy.yml@%s" .EngineRef)}}
    with:
{{- if not .AIEnabled}}
      ai: false
{{- end}}
      # Repository variables keep provider coordinates out of project.yaml.
      ai-api: ${{"{{"}} vars.AI_API {{"}}"}}
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
`))

var k8sValuesTmpl = template.Must(template.New("values.yaml").Funcs(yamlTemplateFuncs).Parse(
	`# yaml-language-server: $schema=https://raw.githubusercontent.com/willie-yao/prow-ai-dashboard/{{urlPath .EngineRef}}/deploy/helm/prow-ai-dashboard/values.schema.json
# Generated by prow-ai-dashboard onboard.
#
# Active values below are settings a new consumer commonly owns. Commented
# values document optional chart features without pinning their current defaults.
# If the installed chart version differs from the engine ref above, use the
# schema that ships with that chart version.
#
# The Kubernetes deploy wrapper passes project.yaml, prompts/system.md, and
# skills/* separately with --set-file.
#
# Full values reference:
# https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/deploy/helm/prow-ai-dashboard/values.yaml
#
# For a published chart version:
# helm show values oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
#   --version <chart-version>

# Empty tag overrides let stable chart upgrades follow the chart appVersion
# instead of retaining an older snapshot through reused values.
global:
  # Empty follows the chart appVersion.
  imageTag: ""

image:
  # Defaults to the engine image repository from the chart.
  # repository: ghcr.io/willie-yao/prow-ai-dashboard
  tag: ""
  # pullPolicy: IfNotPresent

# watch runs a continuously refreshing worker Deployment.
# cron runs a scheduled fetcher CronJob.
# Both modes must keep exactly one writer on the shared volume.
mode: watch

# The volume contains dashboard data and AI cache state. ReadWriteMany is
# required for the writer and server. existingClaim reuses a pre-provisioned
# PVC. retain protects chart-managed data during removal or claim changes.
persistence:
  enabled: true
  existingClaim: ""
  storageClass: "<your-rwx-storage-class>"
  accessMode: ReadWriteMany
  size: 1Gi
  retain: true

ai:
  enabled: {{.AIEnabled}}
  api: {{quote .AIAPI}}
  endpoint: {{quote .AIEndpoint}}
  model: {{quote .AIModel}}
  # 0 uses provider metadata or the engine fallback. Set a nonzero value only
  # when the endpoint's documented context window supports it.
  contextWindowTokens: 0
  # The chart never creates external provider credentials. Reference a Secret
  # managed outside this file. When enabling AI later, set this field first.
  existingSecret: {{if .AIEnabled}}{{quote (printf "%s-ai" .Namespace)}}{{else}}""{{end}}
  tokenSecretKey: AI_TOKEN

  # Public repositories normally use anonymous source reads. Private source
  # grounding should use a separate read-only GitHub credential Secret.
  githubReadTokenSecretName: ""
  githubReadTokenSecretKey: GITHUB_READ_TOKEN

fetcher:
  # History depth affects dashboard coverage and fetch cost.
  buildsPerJob: 10
  # Concurrent artifact fetches. Increase only after checking storage limits.
  workers: 5
  # Bounds discovery and artifact fetching. Orka Tasks have a separate timeout.
  timeout: 120m

  # Watch-mode cadence. Cron settings below do not schedule a CronJob while
  # mode remains watch.
  watchInterval: 5m
  reconcileInterval: 1h

  # Keep scheduled starts suspended while watch mode is active. Set false only
  # when switching to mode: cron.
  suspend: true

  # Cron-mode settings. Deadlines and retries are separate from model or Orka
  # retries, and apply only when mode is cron.
  # schedule: "0 */6 * * *"
  # concurrencyPolicy: Forbid
  # activeDeadlineSeconds: 36000
  # backoffLimit: -1
  # restartPolicy: ""

  # Optional fetcher environment, resources, and placement:
  # extraEnv: []
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

analysisRuntime:
  # inprocess is the recommended default.
  # orka-container is an experimental opt-in lifecycle sidegrade.
  type: inprocess

  # Enabling these fields does not install Orka. Install and operate a separate
  # Orka release first. The model Secret must exist in the analysis namespace,
  # taskTimeout must exceed the project AI timeout plus startup and result
  # finalization time, and analyzer Tasks must use CPU placement.
  #
  # To use the experimental Orka container runtime, set type to orka-container
  # and uncomment the needed fields inside this existing mapping.
  orkaContainer:
    # namespace: ""
    # api: http://orka.orka-system.svc.cluster.local:8080
    # apiAuth:
    #   existingSecret: ""
    #   tokenKey: token
    # maxConcurrentTasks: 2
    # pollInterval: 2s
    # taskTimeout: 20m
    # retries: 1
    # Empty clears an older image-specific tag during upgrades.
    image:
      # repository: ghcr.io/willie-yao/prow-ai-dashboard/analyzer
      tag: ""
      # pullPolicy: IfNotPresent
    # modelAuth:
    #   existingSecret: "<model-secret-in-analysis-namespace>"
    #   tokenKey: token
    # state:
    #   existingSecret: ""
    #   key: state-key
    # nodeSelector:
    #   agentpool: "<cpu-agentpool>"
    # tolerations: []
    # affinity: {}

# Fix generation is independent of analysisRuntime.type and must also be
# configured in project.yaml. It remains disabled in the generated scaffold.
orka:
  namespace: orka-system

  fixRuntime:
    enabled: false
    # Empty clears an older image-specific tag during upgrades.
    image:
      tag: ""
    # Required before enabling. Match the effective project.yaml fix runtime.
    # admission:
    #   agentRef: "<orka-agent-name>"
    #   repository:
    #     owner: "<github-owner>"
    #     name: "<github-repository>"
    #   maxTurns: 30
    #   allowBash: true
    #   timeout: 10m
    #   retries: 1

  # rbac:
  #   create: true
  #   serviceAccountName: ""

server:
  # Chat is read-only but still authenticated. Enabling chat requires the
  # actions authentication settings and a secure origin.
  chat:
    enabled: false
    # timeout: 2m
    # correctionsEnabled: false

  # Actions enable GitHub writes. admins is a fail-closed allowlist. OAuth and
  # proxy credentials belong in existing Secrets, never in this file. Enabling
  # chat or actions requires secure origin configuration.
  actions:
    enabled: false
    # mode: oauth
    # admins:
    #   - "<github-login>"
    # oauth:
    #   clientId: "<oauth-client-id>"
    #   redirectUrl: "https://dashboard.example.com/api/auth/callback"
    #   privateRepositories: false
    #   existingSecret: "<oauth-secret>"
    # proxy:
    #   header: X-Auth-Request-Email
    #   existingSecret: "<proxy-secret>"

  # ClusterIP behind ingress or an SSO proxy is preferred for authenticated
  # features. Do not expose a public LoadBalancer without origin restrictions.
  service:
    type: ClusterIP
    port: 80
    # loadBalancerSourceRanges: []
    # externalTrafficPolicy: ""
    # internal:
    #   enabled: false
    #   annotations: {}
    # publicOriginAcknowledged: false
    # annotations: {}

  # Optional server resources and placement:
  # resources: {}
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

ingress:
  enabled: false
  # className: nginx
  # annotations: {}
  # hosts:
  #   - host: dashboard.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []

# Enabling NetworkPolicy with an empty ingress list denies all ingress. The
# wizard cannot infer the ingress controller namespace or network topology.
networkPolicy:
  enabled: false
  ingress: []
  # To allow an ingress controller to the server container port, change the
  # ingress value above from [] to a list and add:
  #   - from:
  #       - namespaceSelector:
  #           matchLabels:
  #             kubernetes.io/metadata.name: ingress-nginx
  #     ports:
  #       - protocol: TCP
  #         port: 8080

# The chart also provides non-root pod and container security defaults.
# Override them only after reviewing the complete chart values.
`))

var k8sDeployReadmeTmpl = template.Must(template.New("README.md").Funcs(readmeTemplateFuncs).Parse(
	`# Deploy {{.Name}} with Helm

This guide contains the project-specific first install for ` + "`{{.DashboardName}}`" + `.
Run every command from the consumer repository root.

The default deployment uses the in-process analysis runtime. It does not install
or require Orka.

## Consumer files

Keep these files together:

` + "```text" + `
project.yaml
prompts/system.md
skills/*.yaml
skills/*.yml
deploy/values.yaml
deploy/README.md
` + "```" + `

The ` + "`skills/`" + ` directory is optional unless ` + "`project.yaml`" + ` requires a
consumer skill bundle.

## Set local variables

Review the context and chart version before any live command:

` + "```bash" + `
export PROJECT_DIR="$PWD"
export ENGINE_DIR="$HOME/src/prow-ai-dashboard"
export ENGINE_REF={{shellquote .EngineRef}}
export RELEASE={{shellquote .Namespace}}
export NAMESPACE={{shellquote .Namespace}}
export CONTEXT="<your-kubernetes-context>"
export CHART_VERSION="<published-chart-version>"
` + "```" + `

Helm 4 is required for live install and rollback support. The context remains
explicit in every cluster command. Choose a published release from
https://github.com/willie-yao/prow-ai-dashboard/releases. For a stable install,
use an engine tag and chart version from the same release. Chart versions omit
the leading ` + "`v`" + ` used by Git tags.

## Prepare the deployment helper

Use a dedicated, clean engine checkout. If it already exists, the clean-tree
check prevents this guide from replacing local changes.

` + "```bash" + `
if [ ! -d "$ENGINE_DIR/.git" ]; then
  git clone https://github.com/willie-yao/prow-ai-dashboard.git "$ENGINE_DIR"
fi

if [ -n "$(git -C "$ENGINE_DIR" status --porcelain)" ]; then
  printf 'Engine checkout has local changes: %s\n' "$ENGINE_DIR" >&2
else
  if git -C "$ENGINE_DIR" fetch --tags origin "$ENGINE_REF" &&
    git -C "$ENGINE_DIR" checkout --detach FETCH_HEAD &&
    make -C "$ENGINE_DIR" build; then
    export FETCHER="$ENGINE_DIR/bin/fetcher"
    printf 'Fetcher ready: %s\n' "$FETCHER"
  fi
fi
` + "```" + `

## Understand deploy/values.yaml

Active values are common settings this consumer owns. Commented values document
optional features without pinning their chart defaults.

- ` + "`mode: watch`" + ` is the recommended first deployment. ` + "`mode: cron`" + `
  settings are present as comments for a later intentional switch.
- Persistence, AI, history depth, worker count, timeout, and watch cadence are
  active and should be reviewed.
- ` + "`analysisRuntime.type: inprocess`" + ` is the recommended default. Orka is
  experimental, separately installed, and disabled.
- Chat, write actions, ingress, and NetworkPolicy remain disabled. Chat and
  actions require authentication and secure origin configuration before exposure.

Print the complete values for the chart version you plan to install:

` + "```bash" + `
helm show values \
  oci://ghcr.io/willie-yao/charts/prow-ai-dashboard \
  --version "$CHART_VERSION"
` + "```" + `

The values header points compatible YAML editors at the schema from this engine
reference. If the installed chart version differs, use the schema that ships
with that chart version.

The matching source reference is:
https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/deploy/helm/prow-ai-dashboard/values.yaml

## Review the generated configuration

1. Review ` + "`project.yaml`" + ` and the inferred categories.
2. Review every claim and TODO in ` + "`prompts/system.md`" + `.
3. Edit ` + "`deploy/values.yaml`" + ` and replace
   ` + "`<your-rwx-storage-class>`" + `, or set ` + "`persistence.existingClaim`" + `.
{{if .AIEnabled}}4. Confirm ` + "`ai.api`" + `, ` + "`ai.endpoint`" + `, and ` + "`ai.model`" + `.
5. Keep ` + "`ai.existingSecret`" + ` set to ` + "`{{.Namespace}}-ai`" + `. The Secret is
   created during live setup below.
{{else}}4. AI is disabled in the initial scaffold. No provider Secret is required.
   To enable it later, set ` + "`ai.enabled=true`" + `, configure the provider, and
   reference an existing Secret through ` + "`ai.existingSecret`" + `.
{{end}}
Keep the first deployment small. Leave chat, write actions, ingress,
NetworkPolicy, and Orka disabled until the expected jobs are published.

## Validate the bundle locally

Run the read-only doctor:

` + "```bash" + `
"$FETCHER" onboard doctor \
  -project-dir "$PROJECT_DIR"
` + "```" + `

Doctor validates the project, prompt, deployment values, credential source, and
Prow discovery. It does not contact the model endpoint or inspect the cluster.

Render the chart locally without cluster writes:

` + "```bash" + `
"$FETCHER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION" \
  --dry-run
` + "```" + `

The dry run requires a non-empty context so the command can be reused for the
live install, but it does not contact that context or print rendered Secrets.

## Select the context and storage class

List local contexts:

` + "```bash" + `
kubectl config get-contexts
` + "```" + `

Confirm the selected cluster and list its storage classes:

` + "```bash" + `
kubectl --context "$CONTEXT" cluster-info
kubectl --context "$CONTEXT" get storageclass
` + "```" + `

Confirm with the storage driver documentation that the selected class supports
` + "`ReadWriteMany`" + `, then update ` + "`persistence.storageClass`" + `. Kubernetes does
not report access-mode support directly on the StorageClass object.

## Live setup and install

The commands in this section write to ` + "`$CONTEXT`" + `.

Create the namespace idempotently:

` + "```bash" + `
kubectl --context "$CONTEXT" create namespace "$NAMESPACE" \
  --dry-run=client \
  -o yaml |
kubectl --context "$CONTEXT" apply -f -
` + "```" + `

{{if .AIEnabled}}Create the AI Secret from a token file outside the repository. The Secret name
matches the generated ` + "`ai.existingSecret`" + ` value exactly.

` + "```bash" + `
export AI_TOKEN_FILE="$HOME/.config/prow-ai-dashboard/ai-token"

install -d -m 700 "$(dirname "$AI_TOKEN_FILE")"
if [ ! -s "$AI_TOKEN_FILE" ]; then
  printf 'AI token: '
  IFS= read -r -s AI_TOKEN
  printf '\n'
  if [ -n "${AI_TOKEN:-}" ]; then
    printf '%s' "$AI_TOKEN" >"$AI_TOKEN_FILE"
    chmod 600 "$AI_TOKEN_FILE"
  fi
  unset AI_TOKEN
fi

if [ -s "$AI_TOKEN_FILE" ]; then
  kubectl --context "$CONTEXT" \
    --namespace "$NAMESPACE" \
    create secret generic {{shellquote (printf "%s-ai" .Namespace)}} \
    --from-file=AI_TOKEN="$AI_TOKEN_FILE" \
    --dry-run=client \
    -o yaml |
  kubectl --context "$CONTEXT" \
    --namespace "$NAMESPACE" \
    apply -f -
else
  printf 'AI Secret was not created because the token file is empty.\n' >&2
fi
` + "```" + `

The token value is read from the file. It is not printed or placed in the
command line. Prefer the cluster's normal Secret manager for production.

{{end}}Install the dashboard:

` + "```bash" + `
"$FETCHER" kubernetes install \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

The wrapper refuses an existing release, includes the current project, prompt,
and skills, waits for readiness, and rolls back a failed install.

## Verify the first fetch

Inspect the workloads and persistent claim:

` + "```bash" + `
kubectl --context "$CONTEXT" \
  --namespace "$NAMESPACE" \
  get deploy,pod,pvc
` + "```" + `

Follow the watch worker by its stable release and component labels:

` + "```bash" + `
WORKER_DEPLOYMENT=$(kubectl --context "$CONTEXT" \
  --namespace "$NAMESPACE" \
  get deployment \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=worker" \
  -o jsonpath='{.items[0].metadata.name}')

test -n "$WORKER_DEPLOYMENT"
kubectl --context "$CONTEXT" \
  --namespace "$NAMESPACE" \
  logs -f "deployment/$WORKER_DEPLOYMENT"
` + "```" + `

A successful first run has a Bound RWX PVC, ready worker and server Deployments,
a completed fetch, and the expected jobs in the dashboard.

## Open the dashboard

Resolve the server Service through the same stable labels:

` + "```bash" + `
SERVER_SERVICE=$(kubectl --context "$CONTEXT" \
  --namespace "$NAMESPACE" \
  get service \
  -l "app.kubernetes.io/instance=$RELEASE,app.kubernetes.io/component=server" \
  -o jsonpath='{.items[0].metadata.name}')

test -n "$SERVER_SERVICE"
kubectl --context "$CONTEXT" \
  --namespace "$NAMESPACE" \
  port-forward "service/$SERVER_SERVICE" 8080:80
` + "```" + `

Open http://localhost:8080 and verify the published manifest:

` + "```bash" + `
curl --fail http://localhost:8080/data/manifest.json
` + "```" + `

## Upgrade

Set a reviewed published chart version, validate locally, then run the live
upgrade:

` + "```bash" + `
export CHART_VERSION="<new-published-chart-version>"

"$FETCHER" kubernetes upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION" \
  --dry-run

"$FETCHER" kubernetes upgrade \
  --project-dir "$PROJECT_DIR" \
  --values deploy/values.yaml \
  --release "$RELEASE" \
  --namespace "$NAMESPACE" \
  --kube-context "$CONTEXT" \
  --chart-version "$CHART_VERSION"
` + "```" + `

Every upgrade includes the current project, prompt, and skills. It starts from
the new chart defaults, reapplies prior user-supplied values, then applies this
consumer configuration and bundle. It waits for readiness and rolls back on
failure.

## More configuration

- First-run Kubernetes quickstart:
  https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/docs/kubernetes.md
- Architecture, modes, manual Helm, and advanced values:
  https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/docs/kubernetes-reference.md
- Optional separate Orka installation and runtime integration:
  https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/docs/orka.md
- Troubleshooting:
  https://github.com/willie-yao/prow-ai-dashboard/blob/{{urlPath .EngineRef}}/docs/troubleshooting.md
`))

var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. Replace the TODOs with a grounded diagnostic runbook.
Use only project documentation, job configuration, source, and observed CI
artifacts. Leave an item unresolved instead of adding plausible guidance.

The analyzer can read supplied Prow artifacts. If Kubernetes artifact tools are
enabled, they navigate Kubernetes-shaped logs and resource dumps already in the
artifact tree. The analyzer does not connect to a live Kubernetes API and does
not have portal, SSH, arbitrary shell, browser, or local CLI access.

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe only component and resource relationships that help localize
failures. -->

## Diagnostic lifecycle

<!-- TODO: describe the relevant provisioning, initialization, reconciliation,
test, and cleanup sequence. Require conditions and timestamped logs to prove the
stalled phase. -->

## Test and job flavors

<!-- TODO: describe test families and environment flavors established by project
documentation or job configuration. Require the analyzer to identify the actual
flavor before applying flavor-specific guidance. -->

## Artifact layout

<!-- TODO: list exact project-specific artifact paths only when documented, and
state what each artifact proves. Label universal Prow files as defaults. -->

## Common failure patterns

<!-- TODO: for each supported pattern, name the signal, required evidence, causal
conclusion to avoid, and remediation boundary. -->

## Transient classification

<!-- TODO: add only project-supported transient rules. Each rule must state the
positive run evidence that permits the classification and the evidence or
persistence that makes the failure non-transient. Do not add generic classes. -->

## Triage order

<!-- TODO: provide an artifact-first sequence from failing JUnit detail and
build-log.txt to resource conditions, component logs, and a passing comparison. -->

## Relevant source repositories

<!-- TODO: list only grounded GitHub owner/name repositories that can produce
actionable relevant_files paths. -->

## Unresolved details

<!-- TODO: list important artifact paths, flavors, dependency chains, failure
boundaries, or repositories that the available sources do not establish. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`prow-ai-dashboard onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- Review the ` + "`prompts/system.md`" + ` draft. Replace any TODOs and confirm its
  project-specific claims. Prompt quality is the biggest lever on analysis depth.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow
{{if .AIEnabled}}# Set the deployed provider coordinates and token. The onboarding drafting
# provider is separate and is not configured by these values.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{else}}# AI is disabled in the initial workflow. To enable it later, remove ` + "`ai: false`" + `
# from .github/workflows/deploy.yml, then configure the provider coordinates and token.
gh variable set AI_API --body {{.AIAPI}} --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_ENDPOINT --repo {{.DashboardOwner}}/{{.DashboardName}}
gh variable set AI_MODEL --repo {{.DashboardOwner}}/{{.DashboardName}}
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
{{end}}` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/prow-ai-dashboard/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
	AIEnabled      bool
	AIAPI          string
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
