package onboard

import (
	"strings"
	"text/template"

	"github.com/willie-yao/prow-ai-dashboard/backend/internal/project"
)

// scaffoldData is the input to all scaffold templates.
type scaffoldData struct {
	ID                string
	Name              string
	DiscoveryTestGrid string // non-empty for testgrid discovery
	BucketDiscovery   bool   // true for bucket discovery
	Provider          string // "gcs" or "gcsweb"
	Bucket            string
	GCSWebBase        string // gcsweb gateway root
	Title             string
	BasePath          string
	SiteURL           string
	SourceOwner       string
	SourceName        string
	Categories        []project.CategoryRule
	IncludePresubmits bool
	EngineRef         string
	Mode              string // "pages" or "k8s"
	AIEndpoint        string // seeds deploy/values.yaml ai.endpoint (k8s mode)
	AIModel           string // seeds deploy/values.yaml ai.model (k8s mode)
	Namespace         string // k8s namespace / helm release name (k8s mode)
	DashboardName     string // dashboard repo name; the scaffold's directory
}

var projectYAMLTmpl = template.Must(template.New("project.yaml").Parse(
	`# Generated by prow-ai-dashboard onboard. Review and edit before deploying.
id: {{.ID}}
name: "{{.Name}}"
{{if .DiscoveryTestGrid}}
# Jobs advertising this testgrid dashboard are discovered automatically.
testgrid:
  dashboard: "{{.DiscoveryTestGrid}}"
{{else}}
# Jobs are discovered by listing the storage bucket's own job indexes.
discovery:
  source: bucket
{{- if .IncludePresubmits}}
{{- end}}
{{end}}
# Where this project's Prow build artifacts live.
storage:
  provider: {{.Provider}}
  bucket: "{{.Bucket}}"
{{- if .GCSWebBase}}
  base: "{{.GCSWebBase}}"
{{- end}}
{{if .Categories}}
# Job grouping. First substring match wins; unmatched jobs go in "other".
# Generated from job-name clustering: review, reorder, and relabel as needed.
categories:
{{- range .Categories}}
  - match: "{{.Match}}"
    id: "{{.ID}}"
    label: "{{.Label}}"
{{- end}}
{{end}}
# UI branding.
branding:
  title: "{{.Title}}"
  base_path: "{{.BasePath}}"
  site_url: "{{.SiteURL}}"
  source_repo:
    owner: "{{.SourceOwner}}"
    name: "{{.SourceName}}"
{{if .IncludePresubmits}}
# This project's dashboard includes presubmit jobs.
source:
  include_presubmits: true
{{end}}`))

var deployYAMLTmpl = template.Must(template.New("deploy.yml").Parse(
	`name: Deploy Dashboard

# Calls the reusable workflow in willie-yao/prow-ai-dashboard to build and
# deploy this repo's Prow dashboard to GitHub Pages.

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    uses: willie-yao/prow-ai-dashboard/.github/workflows/reusable-deploy.yml@{{.EngineRef}}
    with:
      project_dir: "."
      builds: 10
      ai: true
      # Headroom for a cold full re-analysis with the critique retry loop;
      # the AI cache persists partial progress so each run converges.
      fetch-timeout: "150m"
      # Optional: keep model/endpoint out of the public project.yaml by
      # sourcing them from repo variables. The project.yaml ai.* fields win.
      ai-model: ${{"{{"}} vars.AI_MODEL {{"}}"}}
      ai-endpoint: ${{"{{"}} vars.AI_ENDPOINT {{"}}"}}
    secrets:
      AI_TOKEN: ${{"{{"}} secrets.AI_TOKEN {{"}}"}}
      # Optional: uncomment to enable the matching feature.
      # SLACK_WEBHOOK_URL: ${{"{{"}} secrets.SLACK_WEBHOOK_URL {{"}}"}}
      # ISSUE_TOKEN: ${{"{{"}} secrets.ISSUE_TOKEN {{"}}"}}
`))

var clearCacheYAMLTmpl = template.Must(template.New("clear-cache.yml").Parse(
	`name: Clear AI Cache

# Manually wipe this repo's data cache so the next deploy refetches
# everything and regenerates AI summaries.

on:
  workflow_dispatch: {}

permissions:
  actions: write

jobs:
  clear:
    uses: willie-yao/prow-ai-dashboard/.github/workflows/reusable-clear-cache.yml@{{.EngineRef}}
    with:
      project_dir: "."
`))

var k8sValuesTmpl = template.Must(template.New("values.yaml").Parse(
	`# Helm values for the Kubernetes-native deploy of this dashboard.
#
# Consumed by the engine chart at
# willie-yao/prow-ai-dashboard/deploy/helm/prow-ai-dashboard. project.yaml and
# prompts/system.md are passed separately via --set-file (see deploy/README.md).

image:
  # Pin to a release tag once one ships, or track :main for the latest engine.
  tag: main

# Continuous in-cluster worker (single writer) co-located with the model.
mode: watch

# Shared RWX volume so the worker (writer) and server (reader) mount it at once.
persistence:
  # Set to your cluster's ReadWriteMany class (azurefile-csi on AKS,
  # efs-sc on EKS, filestore on GKE, ...).
  storageClass: "<your-rwx-storage-class>"
  accessMode: ReadWriteMany
  size: 1Gi

# AI analysis. Point at an OpenAI-compatible chat-completions endpoint reachable
# from inside the cluster; provide the token at install time, not in this file.
ai:
  enabled: true
  endpoint: "{{if .AIEndpoint}}{{.AIEndpoint}}{{else}}http://<your-model-svc>.<ns>.svc.cluster.local:8000/v1/chat/completions{{end}}"
  model: "{{if .AIModel}}{{.AIModel}}{{else}}<your-model-id>{{end}}"

# Fetch depth and cadence. Raise fetcher.timeout for slow self-hosted models so
# a cold serial pass fits in one per-pass budget.
fetcher:
  buildsPerJob: 10
  workers: 4
  timeout: 120m
  watchInterval: 5m
  reconcileInterval: 1h

# Optional: admin-gated File issue / Propose fix buttons (Kubernetes-native
# only). Register a GitHub OAuth App (see deploy/README.md), then uncomment:
# server:
#   actions:
#     enabled: true
#     mode: oauth
#     admins: [<your-github-login>]
#     oauth:
#       clientId: "<oauth-app-client-id>"
#       existingSecret: {{.Namespace}}-oauth   # keys: OAUTH_CLIENT_SECRET, SESSION_KEY
#       redirectUrl: "https://<dashboard-host>/api/auth/callback"
`))

var k8sDeployReadmeTmpl = template.Must(template.New("deploy/README.md").Parse(
	`# Deploying (Kubernetes-native)

This dashboard runs in-cluster next to the model: a worker fetches builds and
runs the analysis against an in-cluster endpoint, and a server serves the SPA
plus the ` + "`/data/*.json`" + ` contract from a shared volume. No GitHub Actions or
Pages. See the engine's
[docs/kubernetes.md](https://github.com/willie-yao/prow-ai-dashboard/blob/{{.EngineRef}}/docs/kubernetes.md)
for the full reference.

## Prerequisites

- A cluster with an OpenAI-compatible chat-completions endpoint reachable over
  cluster DNS (set ` + "`ai.endpoint`" + ` / ` + "`ai.model`" + ` in ` + "`deploy/values.yaml`" + `).
- A ` + "`ReadWriteMany`" + ` storage class (set ` + "`persistence.storageClass`" + `).
- A checkout of ` + "`willie-yao/prow-ai-dashboard`" + ` for the Helm chart.

## Install

Run from an engine checkout so the chart path resolves, pointing at this repo
for the consumer config:

` + "```bash" + `
helm upgrade --install {{.Namespace}} deploy/helm/prow-ai-dashboard \
  --namespace {{.Namespace}} --create-namespace \
  -f ../{{.DashboardName}}/deploy/values.yaml \
  --set-file project.config=../{{.DashboardName}}/project.yaml \
  --set-file project.systemPrompt=../{{.DashboardName}}/prompts/system.md \
  --set ai.token=<token>   # any non-empty string if your endpoint needs no key
` + "```" + `

## Access

` + "```bash" + `
kubectl -n {{.Namespace}} port-forward svc/{{.Namespace}}-prow-ai-dashboard-server 8080:80
open http://localhost:8080
` + "```" + `

Follow the worker as it populates data:

` + "```bash" + `
kubectl -n {{.Namespace}} logs -f deploy/{{.Namespace}}-prow-ai-dashboard-worker
` + "```" + `

The first cold pass can be slow on a self-hosted model; the dashboard fills in
once the pass completes.
`))

var k8sChecklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding (Kubernetes-native)

This scaffold was generated by ` + "`prow-ai-dashboard onboard -mode k8s`" + `. The job
sweep confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- ` + "`prompts/system.md`" + ` is a **stub**: fill it in with project-specific
  knowledge. This is the single biggest lever on analysis quality.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.
- ` + "`deploy/values.yaml`" + `: set ` + "`persistence.storageClass`" + ` (a ReadWriteMany
  class) and the ` + "`ai.endpoint`" + ` / ` + "`ai.model`" + ` for your in-cluster provider.

## 2. Install with Helm

From a checkout of ` + "`willie-yao/prow-ai-dashboard`" + ` (for the chart), follow
` + "`deploy/README.md`" + `. In short:

` + "```bash" + `
helm upgrade --install {{.Namespace}} deploy/helm/prow-ai-dashboard \
  --namespace {{.Namespace}} --create-namespace \
  -f ../{{.DashboardName}}/deploy/values.yaml \
  --set-file project.config=../{{.DashboardName}}/project.yaml \
  --set-file project.systemPrompt=../{{.DashboardName}}/prompts/system.md \
  --set ai.token=<token>
` + "```" + `

## 3. Optional: interactive actions

To enable the admin-gated **File issue** / **Propose fix** buttons, register a
GitHub OAuth App and uncomment the ` + "`server.actions`" + ` block in
` + "`deploy/values.yaml`" + `. See
https://github.com/willie-yao/prow-ai-dashboard/blob/{{.EngineRef}}/docs/server.md
for the OAuth setup.

The chart pins the engine image via ` + "`image.tag`" + ` in ` + "`deploy/values.yaml`" + `
(defaults to ` + "`main`" + `); see
https://github.com/willie-yao/prow-ai-dashboard/blob/{{.EngineRef}}/docs/releasing.md
to pin a release instead.
`))

var systemPromptTmpl = template.Must(template.New("system.md").Parse(
	`# {{.Name}} AI prompt addendum

This file is concatenated between the engine's universal Prow base prompt and
its JSON response schema. Replace the placeholder below with project-specific
knowledge: the architecture under test, the failure surface, where evidence
lives in the artifacts, and the known transient/flake classes. The richer this
is, the deeper the analysis. See an example at
https://github.com/willie-yao/capz-prow-ai-dashboard/blob/main/prompts/system.md

---

You are debugging {{.Name}} CI test failures.

## Architecture

<!-- TODO: describe the system under test and how its components relate. -->

## Where the evidence lives

<!-- TODO: name the key artifacts (build-log.txt, per-component logs, resource
dumps) and what each is good for. -->

## Known transient / flake classes

<!-- TODO: list infrastructure flakes that should be classified transient (and
NOT turned into a "real bug" verdict), e.g. registry pull timeouts, quota
exhaustion, API server still starting. -->
`))

var checklistTmpl = template.Must(template.New("CHECKLIST.md").Parse(
	`# {{.Name}} dashboard: finish onboarding

This scaffold was generated by ` + "`prow-ai-dashboard onboard`" + `. The job sweep
confirmed your discovery config finds jobs. Remaining steps need a human:

## 1. Review the generated files (required)

- ` + "`prompts/system.md`" + ` is a **stub**: fill it in with project-specific
  knowledge. This is the single biggest lever on analysis quality.
- ` + "`project.yaml`" + ` ` + "`categories`" + ` were inferred from job names; reorder,
  rename, or trim them.

## 2. Place the files in the dashboard repo

Dedicated repo: copy these into the repo root (` + "`project_dir: \".\"`" + `).
Existing repo: put them in a subdir and set ` + "`project_dir`" + ` in the workflows.

## 3. GitHub configuration (the agent can't do this for you)

` + "```bash" + `
# Enable Pages with the GitHub Actions build source:
gh api -X POST repos/{{.DashboardOwner}}/{{.DashboardName}}/pages \
  -f build_type=workflow

# Set the AI token secret (a token your chat-completions endpoint accepts):
gh secret set AI_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}

# Optional: GitHub issue auto-filing (a token with issues:write on the target):
# gh secret set ISSUE_TOKEN --repo {{.DashboardOwner}}/{{.DashboardName}}
# Optional: Slack notifications:
# gh secret set SLACK_WEBHOOK_URL --repo {{.DashboardOwner}}/{{.DashboardName}}
` + "```" + `

## 4. First deploy

Push to ` + "`main`" + ` (or run the **Deploy Dashboard** workflow manually). The
workflows pin the engine at ` + "`@{{.EngineRef}}`" + `; see
https://github.com/willie-yao/prow-ai-dashboard/blob/main/docs/releasing.md
to pin an exact release instead.
`))

// checklistData is the input the checklist template needs.
type checklistData struct {
	Name           string
	DashboardOwner string
	DashboardName  string
	EngineRef      string
	Namespace      string // k8s namespace / helm release (k8s mode only)
}

// renderProjectYAML renders and returns the project.yaml text, collapsing the
// blank lines that conditional template blocks leave behind.
func renderProjectYAML(d scaffoldData) (string, error) {
	var b strings.Builder
	if err := projectYAMLTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return collapseBlankLines(b.String()), nil
}

// collapseBlankLines squeezes runs of blank lines down to one, tidying the
// output left by conditional template sections.
func collapseBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var out []string
	prevBlank := false
	for _, ln := range lines {
		blank := strings.TrimSpace(ln) == ""
		if blank && prevBlank {
			continue
		}
		out = append(out, ln)
		prevBlank = blank
	}
	return strings.TrimLeft(strings.Join(out, "\n"), "\n")
}
